# Generated by Django 3.2.7 on 2021-10-04 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_auto_20211001_0000'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
