# Generated by Django 3.2.7 on 2021-10-04 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_delete_message'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SignLogin',
            new_name='SignUp',
        ),
    ]
