# Generated by Django 3.2.7 on 2021-10-04 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_delete_signup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=15)),
                ('content', models.CharField(default='', max_length=10000)),
            ],
            options={
                'ordering': ['username'],
            },
        ),
    ]
