# Generated by Django 3.2.7 on 2021-10-04 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_posting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(default='', max_length=15)),
                ('email', models.TextField(default='')),
                ('password', models.CharField(default='', max_length=20)),
                ('token', models.TextField(default='')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterModelOptions(
            name='posting',
            options={'ordering': ['nickname']},
        ),
        migrations.RenameField(
            model_name='posting',
            old_name='username',
            new_name='nickname',
        ),
        migrations.AddField(
            model_name='posting',
            name='token',
            field=models.TextField(default=''),
        ),
    ]
