# Generated by Django 3.2.7 on 2021-10-04 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_auto_20211005_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='image',
            field=models.ImageField(null=True, upload_to='common'),
        ),
    ]
